# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Venper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Venper
  pod 'FirebaseMessaging'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

end

target 'Venper-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Venper-tvOS

  target 'Venper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
